get recommended and similar movies
nCubed/TheMovieDbWrapper pull request #45
Opened 2022-07-25 10:29 UTC by bariscanyilmaz

Added [Recommendations](https://developers.themoviedb.org/3/movies/get-movie-recommendations) and [Similar](https://developers.themoviedb.org/3/movies/get-similar-movies) movies feature

2022-07-27 20:44 UTC, nCubed commented
Thanks for the PR. I've been a bit backed up, but will review in detail in the next couple of days. Cheers!

2022-08-03 14:51 UTC, nCubed commented on DM.MovieApi.IntegrationTests/MovieDb/Movies/ApiMovieRequestTests.cs
> +
Undo the changes to this file as the only change are extra lines.

2022-08-03 14:55 UTC, nCubed commented on DM.MovieApi.IntegrationTests/MovieDb/Movies/ApiMovieRequestTests_GetRecommendations.cs
> +
Remove extra lines in file.

2022-08-03 14:56 UTC, nCubed commented on DM.MovieApi.IntegrationTests/MovieDb/Movies/ApiMovieRequestTests_GetRecommendations.cs
> +
Remove extra lines in methods.

2022-08-03 14:56 UTC, nCubed commented on DM.MovieApi.IntegrationTests/MovieDb/Movies/ApiMovieRequestTests_GetRecommendations.cs
> +}
All files should have a newline at the end.

2022-08-03 14:57 UTC, nCubed commented on DM.MovieApi.IntegrationTests/MovieDb/Movies/ApiMovieRequestTests_GetSimilar.cs
> +        public async Task GetSimilarsAsync_Returns_ValidResults()
Fix the spelling error in method name.

2022-08-03 14:57 UTC, nCubed commented on DM.MovieApi/MovieDb/Movies/ApiMovieRequest.cs
> +                {"append_to_response", "keywords"},
If using "append_to_response", then the backing integration tests must test the "keywords" are present in the response.

2022-08-03 14:58 UTC, nCubed commented on DM.MovieApi/MovieDb/Movies/ApiMovieRequest.cs
> +                {"append_to_response", "keywords"},
If using "append_to_response", then the backing integration tests must test the "keywords" are present in the response.

2022-08-03 15:00 UTC, nCubed requested changes
I have left a few comments on each of the files; please update accordingly. Also, I have just committed a new .editorconfig file to the master branch which has the formatting rules you need to use to follow the same formatting used in the repo.

For the backing integration tests, it would be helpful if you could create some additional tests to validate expected data. See other areas of the integration tests for examples. Do you best; I can add more later as it can be a bit confusing.

2022-08-07 16:57 UTC, bariscanyilmaz commented
@nCubed could you review

2022-08-07 23:42 UTC, nCubed commented
> @nCubed could you review

Thank you for making your changes. 

1. Were you able to merge in the updated .editorcofig into your branch? Doesn't look like the formatting matches the repositories formatting.
1. Did you try to create more complete integration tests (see initial review)

I'd like to get your PR into the wrapper. We just need to ensure the code is consistent with the repositories style, formatting, and integration testing. As I mentioned in the initial review, if you are not comfortable with creating better tests, just let me know and I'll help out.

2022-08-08 06:27 UTC, bariscanyilmaz commented
> > @nCubed could you review
> 
> Thank you for making your changes.
> 
> 1. Were you able to merge in the updated .editorcofig into your branch? Doesn't look like the formatting matches the repositories formatting.
> 2. Did you try to create more complete integration tests (see initial review)
> 
> I'd like to get your PR into the wrapper. We just need to ensure the code is consistent with the repositories style, formatting, and integration testing. As I mentioned in the initial review, if you are not comfortable with creating better tests, just let me know and I'll help out.

1- I merged your commit to this branch [here is the editor config](https://github.com/bariscanyilmaz/TheMovieDbWrapper/blob/movie-recommendation/.editorconfig)
2- Actually, help would be great because I am not experienced in tesitng.

2022-08-15 14:17 UTC, nCubed commented
I am merging this PR into a new branch and will fix as-needed.

2022-08-15 14:18 UTC, merged